---------------------------------------------------------------------------------
XtalCalculator-2.1.0-rev001  Configuration report
---------------------------------------------------------------------------------
The had configure script found most of the programs. Programs installed in 
non-standard locations may not be found unless the PATH variables are defined.

Use configure --help for more informations on PATH.

Summary of important options:

  * Build architecture     : i686-pc-linux-gnu
  
  * Fortran compiler       : gfortran
  * Fortran compiler flags : -g -O2 -ffree-form 
  * Fortran module flags   : -I

  * C compiler             : gcc
  * C compiler flags       : -g 
 
Configuration complete.
You may now type "make" to build XtalCalculator.
---------------------------------------------------------------------------------
